/*
  Warnings:

  - The values [DELETE_SUPPORT_TICKETS] on the enum `Permission` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Permission_new" AS ENUM ('CREATE_STAFF', 'VIEW_STAFF', 'EDIT_STAFF', 'DELETE_STAFF', 'CREATE_SUPPORT_TICKETS', 'VIEW_SUPPORT_TICKETS', 'EDIT_SUPPORT_TICKETS', 'CREATE_USERS', 'VIEW_USERS', 'EDIT_USERS', 'DELETE_USERS', 'CREATE_FUNDS', 'VIEW_FUNDS', 'EDIT_FUNDS', 'DELETE_FUNDS', 'VIEW_ORDERS', 'EDIT_ORDERS', 'DELETE_ORDERS', 'CREATE_ORDERS', 'CREATE_ROLES', 'VIEW_ROLES', 'EDIT_ROLES', 'DELETE_ROLES', 'CREATE_INSTRUMENTS', 'VIEW_INSTRUMENTS', 'EDIT_INSTRUMENTS', 'DELETE_INSTRUMENTS', 'VIEW_TRADES', 'EDIT_TRADES', 'DELETE_TRADES', 'CREATE_REPORTS', 'EDIT_REPORTS', 'VIEW_REPORTS', 'DELETE_REPORTS', 'VIEW_TRANSACTIONS', 'UPDATE_TRANSACTIONS', 'CREATE_TRANSACTIONS', 'DELETE_TRANSACTIONS', 'UPDATE_TICKETS', 'VIEW_TICKETS');
ALTER TABLE "public"."Role" ALTER COLUMN "permissions" DROP DEFAULT;
ALTER TABLE "Role" ALTER COLUMN "permissions" TYPE "Permission_new"[] USING ("permissions"::text::"Permission_new"[]);
ALTER TYPE "Permission" RENAME TO "Permission_old";
ALTER TYPE "Permission_new" RENAME TO "Permission";
DROP TYPE "public"."Permission_old";
ALTER TABLE "Role" ALTER COLUMN "permissions" SET DEFAULT ARRAY[]::"Permission"[];
COMMIT;
